/* Auto-generated by CMIS2C - CMIS Low Memory Register Map */
#ifndef __CMIS_LOW_MEMORY_H
#define __CMIS_LOW_MEMORY_H

#include <stdint.h>

typedef enum {
    Enums_ModuleState_Reserved_0 = 0,  /**< - **/
    Enums_ModuleState_ModuleLowPwr = 1,  /**< ModuleLowPwr **/
    Enums_ModuleState_ModulePwrUp = 2,  /**< ModulePwrUp **/
    Enums_ModuleState_ModuleReady = 3,  /**< ModuleReady **/
    Enums_ModuleState_ModulePwrDn = 4,  /**< ModulePwrDn **/
    Enums_ModuleState_ModuleFault = 5,  /**< ModuleFault **/
    Enums_ModuleState_Reserved_6 = 6,  /**< - **/
    Enums_ModuleState_Reserved_7 = 7,  /**< - **/
} Enums_ModuleState;

/** @brief CMIS Low Memory Register Map (Bytes 0-127) */
typedef struct __attribute__((packed)) {

    /**
     * @brief SFF8024Identifier
     * @details SFF8024Identifier is an SFF-8024 module type Identifier from Table 4-1 “Identifier Values” in [5] which 
     * allowsto infer both physical form factor and management protocol of the module. Note: The CMIS interpretation of 
     * allother registers or fields is valid only when the fundamental SFF8024Identifier indicates that the module uses 
     * theCMIS management protocol.
     * @access RO Rqd.
     */
    uint8_t SFF8024Identifier;  /* r0 */
    /**
     * @brief CmisRevision
     * @details CMIS revision number (decimal): The upper nibble (bits 7-4) is the integer part (major number) The 
     * lowernibble (bits 3-0) is the decimal part (minor number) Example: 01h indicates version 0.1, 21h indicates 
     * version2.1. Note: See Appendix G.3 for interoperability implications of the major revision number (integer 
     * part).
     * @access RO Rqd.
     */
    uint8_t CmisRevision;  /* r1 */
        /**
         * @brief AutoCommissioning
         * @details This field allows modules to support just one of the two intervention-free reconfiguration 
         * procedures,either the regular (automatic DPSM state changing) one or the hot one (staying in DPSM state): 
         * SteppedConfigOnly= 0: xx: both regular and hot supported (legacy default) SteppedConfigOnly = 1: 00: none, 
         * neitherregular nor hot supported 01: only regular supported (affects ApplyDPInit) 10: only hot supported 
         * (affectsApplyImmediate) 11: reserved Effect on ApplyImmediate: When hot intervention-free reconfiguration is 
         * unsupported,the module ignores any WRITE to ApplyImmediate registers Effect on ApplyDPInit: When regular 
         * intervention-freereconfiguration is not supported, the module accepts ApplyDPInit in all states as a 
         * Provisioncommand (see Table 6-4) , but the DPSM excludes the DPReinitT term in the DPDeReinitS transition 
         * signal(see Case 2 in section 6.3.3.1)
         */
        /**
         * @brief MciMaxSpeed
         * @details Indicates maximum supported clock speed of Management Communication Interface (MCI): I2CMCI: 0: 
         * Modulesupports up to 400 kHz 1: Module supports up to 1 MHz 2: Module supports up to 3.4 MHz 3-15: Reserved 
         * SPIMCI:0: Module supports up to 1 MHz 1: Module supports up to 2 MHz 2: Module supports up to 4 MHz 3: 
         * Modulesupports up to 8 MHz 4: Module supports up to 12 MHz 5: Module supports up to 16 MHz 6: Module 
         * supportsup to 20 MHz 7: Module supports up to 30 MHz 8: Module supports up to 40 MHz 9: Module supports up 
         * to50 MHz 10-15: Reserved
         */
        /**
         * @brief SteppedConfigOnly
         * @details Indicates which reconfiguration procedures are supported: 0b: Module supports all types of 
         * reconfigurations:essential step-by-step reconfiguration as well as both types of intervention-free 
         * reconfiguration:hot (in state) and regular (with automatic state change). (legacy default, not meant to be 
         * pre-valent,see notes below) 1b: Module supports the essential step-by-step reconfigura- tion but none or 
         * (optionally)only one of the two types of intervention-free reconfiguration. See the AutoCommissioning field 
         * belowfor more details. Note: The baseline option 1b is assumed to be prevalent for modules that do not 
         * requirehot reconfiguration, such as, e.g., Ethernet transceivers. Note: The extended option 0b with 
         * additionalsupport for intervention-free reconfiguration is intended only for module Applications such as 
         * InfiniBandor Fibre Channel that may require time critical speed negotiations when tight timing is not 
         * achievablewith basic step-by-step configuration. Note: See section 6.2.4 for more information.
         */
        /**
         * @brief MemoryModel
         * @details Indicator of the memory model of the module: 0b: Paged memory (Pages 00h-02h, 10h-11h supported) 
         * 1b:Flat memory (Page 00h supported only)
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t AutoCommissioning : 2;  /* r2.1-0 */
            uint8_t MciMaxSpeed : 4;  /* r2.5-2 */
            uint8_t SteppedConfigOnly : 1;  /* r2.6 */
            uint8_t MemoryModel : 1;  /* r2.7 */
        };
        uint8_t r2;
    };
        /**
         * @brief InterruptDeasserted
         * @details Status of Interrupt output signal 1b: Interrupt not asserted (default) 0b: Interrupt asserted
         */
        /**
         * @brief ModuleState
         * @details Current Module State (see Table 8-7 for encoding and section 6.3.2 for a description of the meaning 
         * ofModuleState) Notes: - Flat memory modules always report ModuleReady. - Not all states of the Module State 
         * Machineare observable.
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t InterruptDeasserted : 1;  /* r3.0 */
            uint8_t ModuleState : 3;  /* r3.3-1 */
            uint8_t _pad_3_4 : 4;
        };
        uint8_t r3;
    };
        /**
         * @brief FlagsSummaryBank0Page11h
         * @details 1b: at least one Flag is set on Bank 0, Page 11h
         * @access RO Rqd.
         */
        /**
         * @brief FlagsSummaryBank0Page12h
         * @details 1b: at least one Flag is set on Bank 0, Page 12h
         * @access RO Adv.
         */
        /**
         * @brief FlagsSummaryBank0Page14h
         * @details 1b: at least one Flag is set on Bank 0, Page 14h
         * @access RO Adv.
         */
        /**
         * @brief FlagsSummaryBank0Page2Ch
         * @details 1b: at least one Flag is set on Bank 0, Page 2Ch
         * @access RO Adv.
         */
    union {
        struct {
            uint8_t FlagsSummaryBank0Page11h : 1;  /* r4.0 */
            uint8_t FlagsSummaryBank0Page12h : 1;  /* r4.1 */
            uint8_t FlagsSummaryBank0Page14h : 1;  /* r4.2 */
            uint8_t FlagsSummaryBank0Page2Ch : 1;  /* r4.3 */
            uint8_t _pad_4_4 : 4;
        };
        uint8_t r4;
    };
        /**
         * @brief FlagsSummaryBank1Page11h
         * @details 1b: at least one Flag is set on Bank 1, Page 11h
         * @access RO Adv.
         */
        /**
         * @brief FlagsSummaryBank1Page12h
         * @details 1b: at least one Flag is set on Bank 1, Page 12h
         * @access RO Adv.
         */
        /**
         * @brief FlagsSummaryBank1Page14h
         * @details 1b: at least one Flag is set on Bank 1, Page 14h
         * @access RO Adv.
         */
        /**
         * @brief FlagsSummaryBank1Page2Ch
         * @details 1b: at least one Flag is set on Bank 1, Page 2Ch
         * @access RO Adv.
         */
    union {
        struct {
            uint8_t FlagsSummaryBank1Page11h : 1;  /* r5.0 */
            uint8_t FlagsSummaryBank1Page12h : 1;  /* r5.1 */
            uint8_t FlagsSummaryBank1Page14h : 1;  /* r5.2 */
            uint8_t FlagsSummaryBank1Page2Ch : 1;  /* r5.3 */
            uint8_t _pad_5_4 : 4;
        };
        uint8_t r5;
    };
        /**
         * @brief FlagsSummaryBank2Page11h
         * @details 1b: at least one Flag is set on Bank 2, Page 11h
         * @access RO Adv.
         */
        /**
         * @brief FlagsSummaryBank2Page12h
         * @details 1b: at least one Flag is set on Bank 2, Page 12h
         * @access RO Adv.
         */
        /**
         * @brief FlagsSummaryBank2Page14h
         * @details 1b: at least one Flag is set on Bank 2, Page 14h
         * @access RO Adv.
         */
        /**
         * @brief FlagsSummaryBank2Page2Ch
         * @details 1b: at least one Flag is set on Bank 2, Page 2Ch
         * @access RO Adv.
         */
    union {
        struct {
            uint8_t FlagsSummaryBank2Page11h : 1;  /* r6.0 */
            uint8_t FlagsSummaryBank2Page12h : 1;  /* r6.1 */
            uint8_t FlagsSummaryBank2Page14h : 1;  /* r6.2 */
            uint8_t FlagsSummaryBank2Page2Ch : 1;  /* r6.3 */
            uint8_t _pad_6_4 : 4;
        };
        uint8_t r6;
    };
        /**
         * @brief FlagsSummaryBank3Page11h
         * @details 1b: at least one Flag is set on Bank 3, Page 11h
         * @access RO Adv.
         */
        /**
         * @brief FlagsSummaryBank3Page12h
         * @details 1b: at least one Flag is set on Bank 3, Page 12h
         * @access RO Adv.
         */
        /**
         * @brief FlagsSummaryBank3Page14h
         * @details 1b: at least one Flag is set on Bank 3, Page 14h
         * @access RO Adv.
         */
        /**
         * @brief FlagsSummaryBank3Page2Ch
         * @details 1b: at least one Flag is set on Bank 3, Page 2Ch
         * @access RO Adv.
         */
    union {
        struct {
            uint8_t FlagsSummaryBank3Page11h : 1;  /* r7.0 */
            uint8_t FlagsSummaryBank3Page12h : 1;  /* r7.1 */
            uint8_t FlagsSummaryBank3Page14h : 1;  /* r7.2 */
            uint8_t FlagsSummaryBank3Page2Ch : 1;  /* r7.3 */
            uint8_t _pad_7_4 : 4;
        };
        uint8_t r7;
    };
        /**
         * @brief ModuleStateChangedFlag
         * @details Latched Flag to indicate a Module State Change
         * @access RO/COR Rqd.
         */
        /**
         * @brief ModuleFirmwareErrorFlag
         * @details Latched Flag to indicate that self-supervision of the main module firmware has detected a failure 
         * inthe main module firmware itself. There are several possible causes of the error such as program memory 
         * becomingcorrupted and incomplete firmware loading.
         * @access RO/COR Adv.
         */
        /**
         * @brief DataPathFirmwareErrorFlag
         * @details Latched Flag to indicate that subordinated firmware in an auxiliary device for processing 
         * transmittedor received signals (e.g. a DSP) has failed.
         * @access RO/COR Adv.
         */
        /**
         * @brief CdbCmdCompleteFlag1
         * @details Latched Flag to indicate completion of a CDB command for CDB instance 1. Support is advertised in 
         * field01h:163.7-6
         * @access RO/COR Adv.
         */
        /**
         * @brief CdbCmdCompleteFlag2
         * @details Latched Flag to indicate completion of a CDB command for CDB instance 2. Support is advertised in 
         * field01h:163.7-6
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t ModuleStateChangedFlag : 1;  /* r8.0 */
            uint8_t ModuleFirmwareErrorFlag : 1;  /* r8.1 */
            uint8_t DataPathFirmwareErrorFlag : 1;  /* r8.2 */
            uint8_t _pad_8_3 : 3;
            uint8_t CdbCmdCompleteFlag1 : 1;  /* r8.6 */
            uint8_t CdbCmdCompleteFlag2 : 1;  /* r8.7 */
        };
        uint8_t r8;
    };
        /**
         * @brief TempMonHighAlarmFlag
         * @details Latched Flag for high temperature alarm
         */
        /**
         * @brief TempMonLowAlarmFlag
         * @details Latched Flag for low temperature alarm
         */
        /**
         * @brief TempMonHighWarningFlag
         * @details Latched Flag for high temperature warning
         */
        /**
         * @brief TempMonLowWarningFlag
         * @details Latched Flag for low temperature warning
         */
        /**
         * @brief VccMonHighAlarmFlag
         * @details Latched Flag for high supply voltage alarm
         */
        /**
         * @brief VccMonLowAlarmFlag
         * @details Latched Flag for low supply voltage alarm
         */
        /**
         * @brief VccMonHighWarningFlag
         * @details Latched Flag for high supply voltage warning
         */
        /**
         * @brief VccMonLowWarningFlag
         * @details Latched Flag for low supply voltage warning
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t TempMonHighAlarmFlag : 1;  /* r9.0 */
            uint8_t TempMonLowAlarmFlag : 1;  /* r9.1 */
            uint8_t TempMonHighWarningFlag : 1;  /* r9.2 */
            uint8_t TempMonLowWarningFlag : 1;  /* r9.3 */
            uint8_t VccMonHighAlarmFlag : 1;  /* r9.4 */
            uint8_t VccMonLowAlarmFlag : 1;  /* r9.5 */
            uint8_t VccMonHighWarningFlag : 1;  /* r9.6 */
            uint8_t VccMonLowWarningFlag : 1;  /* r9.7 */
        };
        uint8_t r9;
    };
        /**
         * @brief Aux1MonHighAlarmFlag
         * @details Latched Flag for high Aux 1 monitor alarm
         */
        /**
         * @brief Aux1MonLowAlarmFlag
         * @details Latched Flag for low Aux 1 monitor alarm
         */
        /**
         * @brief Aux1MonHighWarningFlag
         * @details Latched Flag for high Aux 1 monitor warning
         */
        /**
         * @brief Aux1MonLowWarningFlag
         * @details Latched Flag for low Aux 1 monitor warning
         */
        /**
         * @brief Aux2MonHighAlarmFlag
         * @details Latched Flag for high Aux 2 monitor alarm
         */
        /**
         * @brief Aux2MonLowAlarmFlag
         * @details Latched Flag for low Aux 2 monitor alarm
         */
        /**
         * @brief Aux2MonHighWarningFlag
         * @details Latched Flag for high Aux 2 monitor warning
         */
        /**
         * @brief Aux2MonLowWarningFlag
         * @details Latched Flag for low Aux 2 monitor warning
         * @access RO/COR A dv.
         */
    union {
        struct {
            uint8_t Aux1MonHighAlarmFlag : 1;  /* r10.0 */
            uint8_t Aux1MonLowAlarmFlag : 1;  /* r10.1 */
            uint8_t Aux1MonHighWarningFlag : 1;  /* r10.2 */
            uint8_t Aux1MonLowWarningFlag : 1;  /* r10.3 */
            uint8_t Aux2MonHighAlarmFlag : 1;  /* r10.4 */
            uint8_t Aux2MonLowAlarmFlag : 1;  /* r10.5 */
            uint8_t Aux2MonHighWarningFlag : 1;  /* r10.6 */
            uint8_t Aux2MonLowWarningFlag : 1;  /* r10.7 */
        };
        uint8_t r10;
    };
        /**
         * @brief Aux3MonHighAlarmFlag
         * @details Latched Flag for high Aux 3 monitor alarm
         */
        /**
         * @brief Aux3MonLowAlarmFlag
         * @details Latched Flag for low Aux 3 monitor alarm
         */
        /**
         * @brief Aux3MonHighWarningFlag
         * @details Latched Flag for high Aux 3 monitor warning
         */
        /**
         * @brief Aux3MonLowWarningFlag
         * @details Latched Flag for low Aux 3 monitor warning
         */
        /**
         * @brief CustomMonHighAlarmFlag
         * @details Latched Flag for high Vendor Defined Monitor alarm
         */
        /**
         * @brief CustomMonLowAlarmFlag
         * @details Latched Flag for low Vendor Defined Monitor alarm
         */
        /**
         * @brief CustomMonHighWarningFlag
         * @details Latched Flag for high Vendor Defined Monitor warning
         */
        /**
         * @brief CustomMonLowWarningFlag
         * @details Latched Flag for low Vendor Defined Monitor warning
         * @access RO/COR A dv.
         */
    union {
        struct {
            uint8_t Aux3MonHighAlarmFlag : 1;  /* r11.0 */
            uint8_t Aux3MonLowAlarmFlag : 1;  /* r11.1 */
            uint8_t Aux3MonHighWarningFlag : 1;  /* r11.2 */
            uint8_t Aux3MonLowWarningFlag : 1;  /* r11.3 */
            uint8_t CustomMonHighAlarmFlag : 1;  /* r11.4 */
            uint8_t CustomMonLowAlarmFlag : 1;  /* r11.5 */
            uint8_t CustomMonHighWarningFlag : 1;  /* r11.6 */
            uint8_t CustomMonLowWarningFlag : 1;  /* r11.7 */
        };
        uint8_t r11;
    };
    uint8_t reserved_12[2];  /**< r12.. */
    /**
     * @brief TempMonValue
     * @details S16 Module Temperature Monitor (Current Value) i nternally measured temperature in 1/256 degree Celsius 
     * increments
     * @access RO Adv.
     */
    uint16_t TempMonValue;  /* r14 */
    /**
     * @brief VccMonVoltage
     * @details U16 Supply Voltage Monitor (Current Value) internally measured input supply voltage in 100 µV 
     * increments
     * @access RO Adv.
     */
    uint16_t VccMonVoltage;  /* r16 */
    /**
     * @brief Aux1MonValue
     * @details S16 Aux1 Monitor (see Table 8-49) (Current Value) The monitored observable is advertised in 01h:145.0: 
     * 0b:Custom 1b: TEC Current in 100%/32767 increments of maximum TEC current magnitude, i.e. of the larger of the 
     * heatingor cooling current magnitudes +32767 (100%) of the max current magnitude when heating -32767 is -100% of 
     * themax current magnitude when cooling
     * @access RO Adv.
     */
    uint16_t Aux1MonValue;  /* r18 */
    /**
     * @brief Aux2MonValue
     * @details S16 Aux2 Monitor (see Table 8-49) (Current Value) The monitored observable is advertised in 01h:145.1: 
     * 0b:Laser Temperature: in 1/256 degree Celsius increments 1b: TEC Current in 100%/32767 increments of maximum TEC 
     * currentmagnitude, i.e. of the larger of the heating or cooling current magnitudes +32767 (100%) of the max 
     * currentmagnitude when heating -32767 is -100% of the max current magnitude when cooling
     * @access RO Adv.
     */
    uint16_t Aux2MonValue;  /* r20 */
    /**
     * @brief Aux3MonValue
     * @details S16 Aux3 Monitor (see Table 8-49) (Current Value) The monitored observable is advertised in 01h:145.2: 
     * 0b:Laser Temperature: in 1/256 degree Celsius increments 1b: Additional Supply Voltage: in 100 µV increments
     * @access RO Adv.
     */
    uint16_t Aux3MonValue;  /* r22 */
    /**
     * @brief CustomMonValue
     * @details S 16 or U16: Custom monitor (Current Value)
     * @access RO Adv.
     */
    uint16_t CustomMonValue;  /* r24 */
        /**
         * @brief SoftwareReset
         * @details Self-clearing trigger bit that causes the module to be reset when 1b is written to it. The effect 
         * ofa SoftwareReset trigger is the same as asserting the Reset hardware signal for the appropriate hold time, 
         * followedby its de-assertion. 0b: No action 1b: Software reset
         * @access WO/SC Rqd.
         */
        /**
         * @brief LowPwrRequestSW
         * @details 0b: No request 1b: Request for the module to stay in, or to return into, Low Power mode Note: See 
         * Table6-12 and section 6.3.2.4 for more information
         * @access RW Rqd.
         */
        /**
         * @brief SquelchMethodSelect
         * @details 0b: Squelching of Tx output reduces OMA 1b: Squelching of Tx output reduces P av Advertisement: 
         * 00h:156.5-4Note: Method to choose depends on interface standard used. See Table 8-50 for SquelchMethodSelect 
         * capabilityadvertising.
         * @access RW Adv.
         */
        /**
         * @brief LowPwrAllowRequestHW
         * @details Enables evaluation of the LowPwrRequestHW hardware signal 0b: Module ignores the LowPwrRequestHW 
         * signal1b: Module evaluates the LowPwrRequestHW signal (default) Note: See Table 6-12 and section 6.3.2.2 for 
         * moreinformation Note: As LowPwrRequestSW is cleared by default, evaluation of LowPwrRequestHW is enabled by 
         * default,allowing the host to request start-up to halt in Low Power mode.
         * @access RW Rqd.
         */
        /**
         * @brief BankBroadcastEnable
         * @details 0b: Bank broadcast for lane-banked pages disabled 1b: Bank broadcast for lane-banked pages enabled 
         * WhenBankBroadcastEnable is set, a WRITE to a control register (i.e. to a register with RW or WO access) in 
         * anybank of a lane-banked page is executed as a bank broadcast. Recall that a banked page is lane-banked if 
         * bankingis used to add support for additional lanes. A bank broadcast is a virtually simultaneous and atomic 
         * WRITEof the same value to the same register and the same page, in all supported banks. The module ensures a 
         * generalizedbroadcast register readback condition (see section 5.2.4), such that a READ from any supported 
         * bankfor the same page and register always yields the value written in the broadcasted WRITE. Advertisement: 
         * 01h:156.7
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t _pad_26_0 : 3;
            uint8_t SoftwareReset : 1;  /* r26.3 */
            uint8_t LowPwrRequestSW : 1;  /* r26.4 */
            uint8_t SquelchMethodSelect : 1;  /* r26.5 */
            uint8_t LowPwrAllowRequestHW : 1;  /* r26.6 */
            uint8_t BankBroadcastEnable : 1;  /* r26.7 */
        };
        uint8_t r26;
    };
        /**
         * @brief MciSpeedConfiguration
         * @details For SPIMCI: The host configures the speed used for SPI bus transactions. The module uses this 
         * MciSpeedConfigurationfield to compute the number of fill bytes if it advertises its 
         * AddressDecodingDurationFormatas “time” (0h:213.7 = 1). 0: 1MHz 1: 2MHz 2: 4MHz 3: 8MHz 4: 12MHz 5: 16MHz 6: 
         * 20MHz7: 30MHz 8: 40MHz 9: 50MHz After a change, the next bus transaction uses the new speed. The initial 
         * speedsetting of the module on exit from the MgmtInit state is always 1MHz (MciSpeedConfiguration = 0).
         */
    union {
        struct {
            uint8_t MciSpeedConfiguration : 4;  /* r27.3-0 */
            uint8_t _pad_27_4 : 4;
        };
        uint8_t r27;
    };
    uint8_t reserved_28[3];  /**< r28.. */
        /**
         * @brief ModuleStateChangedMask
         * @details Mask bit for ModuleStateChangedFlag
         * @access RW Rqd.
         */
        /**
         * @brief ModuleFirmwareErrorMask
         * @details Mask bit for ModuleFirmwareErrorFlag
         * @access RW Adv.
         */
        /**
         * @brief DataPathFirmwareErrorMask
         * @details Mask bit for DataPathFirmwareErrorFlag
         * @access RW Adv.
         */
        /**
         * @brief CdbCmdCompleteMask1
         * @details Mask bit for CdbCmdCompleteFlag1
         * @access RW Adv.
         */
        /**
         * @brief CdbCmdCompleteMask2
         * @details Mask bit for CdbCmdCompleteFlag2
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t ModuleStateChangedMask : 1;  /* r31.0 */
            uint8_t ModuleFirmwareErrorMask : 1;  /* r31.1 */
            uint8_t DataPathFirmwareErrorMask : 1;  /* r31.2 */
            uint8_t _pad_31_3 : 3;
            uint8_t CdbCmdCompleteMask1 : 1;  /* r31.6 */
            uint8_t CdbCmdCompleteMask2 : 1;  /* r31.7 */
        };
        uint8_t r31;
    };
        /**
         * @brief TempMonHighAlarmMask
         * @details Mask bit for TempMonHighAlarmFlag
         */
        /**
         * @brief TempMonLowAlarmMask
         * @details Mask bit for TempMonLowAlarmFlag
         */
        /**
         * @brief TempMonHighWarningMask
         * @details Mask bit for TempMonHighWarningFlag
         */
        /**
         * @brief TempMonLowWarningMask
         * @details Mask bit for TempMonLowWarningFlag
         */
        /**
         * @brief VccMonHighAlarmMask
         * @details Mask bit for VccMonHighAlarmFlag
         */
        /**
         * @brief VccMonLowAlarmMask
         * @details Mask bit for VccMonLowAlarmFlag
         */
        /**
         * @brief VccMonHighWarningMask
         * @details Mask bit for VccMonHighWarningFlag
         */
        /**
         * @brief VccMonLowWarningMask
         * @details Mask bit for VccMonLowWarningFlag
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t TempMonHighAlarmMask : 1;  /* r32.0 */
            uint8_t TempMonLowAlarmMask : 1;  /* r32.1 */
            uint8_t TempMonHighWarningMask : 1;  /* r32.2 */
            uint8_t TempMonLowWarningMask : 1;  /* r32.3 */
            uint8_t VccMonHighAlarmMask : 1;  /* r32.4 */
            uint8_t VccMonLowAlarmMask : 1;  /* r32.5 */
            uint8_t VccMonHighWarningMask : 1;  /* r32.6 */
            uint8_t VccMonLowWarningMask : 1;  /* r32.7 */
        };
        uint8_t r32;
    };
        /**
         * @brief Aux1MonHighAlarmMask
         * @details Mask bit for Aux1MonHighAlarmFlag
         */
        /**
         * @brief Aux1MonLowAlarmMask
         * @details Mask bit for Aux1MonLowAlarmFlag
         */
        /**
         * @brief Aux1MonHighWarningMask
         * @details Mask bit for Aux1MonHighWarningFlag
         */
        /**
         * @brief Aux1MonLowWarningMask
         * @details Mask bit for Aux1MonLowWarningFlag
         */
        /**
         * @brief Aux2MonHighAlarmMask
         * @details Mask bit for Aux2MonHighAlarmFlag
         */
        /**
         * @brief Aux2MonLowAlarmMask
         * @details Mask bit for Aux2MonLowAlarmFlag
         */
        /**
         * @brief Aux2MonHighWarningMask
         * @details Mask bit for Aux2MonHighWarningFlag
         */
        /**
         * @brief Aux2MonLowWarningMask
         * @details Mask bit for Aux2MonLowWarningFlag
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t Aux1MonHighAlarmMask : 1;  /* r33.0 */
            uint8_t Aux1MonLowAlarmMask : 1;  /* r33.1 */
            uint8_t Aux1MonHighWarningMask : 1;  /* r33.2 */
            uint8_t Aux1MonLowWarningMask : 1;  /* r33.3 */
            uint8_t Aux2MonHighAlarmMask : 1;  /* r33.4 */
            uint8_t Aux2MonLowAlarmMask : 1;  /* r33.5 */
            uint8_t Aux2MonHighWarningMask : 1;  /* r33.6 */
            uint8_t Aux2MonLowWarningMask : 1;  /* r33.7 */
        };
        uint8_t r33;
    };
        /**
         * @brief Aux3MonHighAlarmMask
         * @details Mask bit for Aux3MonHighAlarmFlag
         */
        /**
         * @brief Aux3MonLowAlarmMask
         * @details Mask bit for Aux3MonLowAlarmFlag
         */
        /**
         * @brief Aux3MonHighWarningMask
         * @details Mask bit for Aux3MonHighWarningFlag
         */
        /**
         * @brief Aux3MonLowWarningMask
         * @details Mask bit for Aux3MonLowWarningFlag
         */
        /**
         * @brief CustomMonHighAlarmMask
         * @details Mask bit for CustomMonHighAlarmFlag
         */
        /**
         * @brief CustomMonLowAlarmMask
         * @details Mask bit for CustomMonLowAlarmFlag
         */
        /**
         * @brief CustomMonHighWarningMask
         * @details Mask bit for CustomMonHighWarningFlag
         */
        /**
         * @brief CustomMonLowWarningMask
         * @details Mask bit for CustomMonLowWarningFlag
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t Aux3MonHighAlarmMask : 1;  /* r34.0 */
            uint8_t Aux3MonLowAlarmMask : 1;  /* r34.1 */
            uint8_t Aux3MonHighWarningMask : 1;  /* r34.2 */
            uint8_t Aux3MonLowWarningMask : 1;  /* r34.3 */
            uint8_t CustomMonHighAlarmMask : 1;  /* r34.4 */
            uint8_t CustomMonLowAlarmMask : 1;  /* r34.5 */
            uint8_t CustomMonHighWarningMask : 1;  /* r34.6 */
            uint8_t CustomMonLowWarningMask : 1;  /* r34.7 */
        };
        uint8_t r34;
    };
    uint8_t reserved_35[2];  /**< r35.. */
    /**
     * @brief CdbStatus1
     * @details Status of the most recent CDB command in CDB instance 1
     * @access RO Adv.
     */
    uint8_t CdbStatus1;  /* r37 */
    /**
     * @brief CdbStatus2
     * @details Status of the most recent CDB command in CDB instance 2
     * @access RO Adv.
     */
    uint8_t CdbStatus2;  /* r38 */
    /**
     * @brief ModuleActiveFirmwareMajorRevision
     * @details U8 Numeric representation of the module’s active firmware major revision
     * @access RO Rqd.
     */
    uint8_t ModuleActiveFirmwareMajorRevision;  /* r39 */
    /**
     * @brief ModuleActiveFirmwareMinorRevision
     * @details U8 Numeric representation of the module’s active firmware minor revision
     * @access RO Rqd.
     */
    uint8_t ModuleActiveFirmwareMinorRevision;  /* r40 */
    /**
     * @brief ModuleFaultCause
     * @details Reason of entering the ModuleFault state 0: No Fault detected (or field not supported) 1: TEC runaway 
     * 2:Data memory corrupted 3: Program memory corrupted 4: Transmitter fault 5: Receiver fault 6: Temperature 
     * relatedfault 7-31: Reserved (fault codes) 32-63: Custom (fault codes) 64-255: Reserved (general)
     * @access RO Opt.
     */
    uint8_t ModuleFaultCause;  /* r41 */
        /**
         * @brief PasswordCmdResult
         * @details Results status for the most recent password entry or password change entry in 00h:118-125 0000b: 
         * notsupported (legacy before CMIS 5.3) 0001b: module password entry or change has been accepted 0010b: host 
         * passwordentry or change has been accepted 0011b: password entry not accepted 1000b: password validation in 
         * progressAdvertisement: 01h:251.3-2
         */
    union {
        struct {
            uint8_t PasswordCmdResult : 4;  /* r42.3-0 */
            uint8_t _pad_42_4 : 4;
        };
        uint8_t r42;
    };
    uint8_t reserved_43[13];  /**< r43.. */
    /**
     * @brief CmisSmSupport
     * @details CMIS State Machines (SM) dynamics supported: 0: undefined transceiver or muxceiver (legacy) 1: no state 
     * machinesupported (e.g. passive cable) 2: MSM only (Resource Module or fixed transceiver) 3: MSM + DPSM 
     * (programmabletransceiver) 4: MSM + DPSM + NPSM (Muxceiver) 5-FF: Reserved Note: When undefined (prior to CMIS 
     * 5.3),the type of module is implicit but can usually be determined from MemoryModel (00h:2) and from other 
     * advertisements.
     * @access RO Rqd.
     */
    uint8_t CmisSmSupport;  /* r56 */
    /**
     * @brief ModuleFunctionType
     * @details 0: Transmission Module 1: ELSFP Resource Module [10] 2-127: Reserved 128-255: Custom
     * @access RO Rqd.
     */
    uint8_t ModuleFunctionType;  /* r57 */
    uint8_t reserved_58[2];  /**< r58.. */
        /**
         * @brief SFF8024ModuleSubtype
         * @details SFF8024ModuleSubtype is an SFF-8024 module subtype identifier, with meaning defined in the 
         * TransceiverSub-type codes table in [5]. It allows the reader to infer information regarding variants of 
         * physicalform factor or thermal characteristics, depending on the SFF8024Identifier value.
         */
    union {
        struct {
            uint8_t SFF8024ModuleSubtype : 4;  /* r60.3-0 */
            uint8_t _pad_60_4 : 4;
        };
        uint8_t r60;
    };
        /**
         * @brief SFF8024FiberFaceType
         * @details Physical contact specification at optical connectors (assumed to be the same for all optical 
         * interfaces)00b: Unknown, unspecified, or not applicable 01b: PC/UPC (Physical/Ultra Physical contact) 10b: 
         * APC(Angled Physical Contact) 11b: Reserved Note: See 00h:203 for connector type information
         */
    union {
        struct {
            uint8_t SFF8024FiberFaceType : 2;  /* r61.1-0 */
            uint8_t _pad_61_2 : 6;
        };
        uint8_t r61;
    };
    /**
     * @brief LowPowerRestrictions
     * @details The module advertises if certain management functions, despite being supported in ModuleReady state, 
     * arenot fully available on entry to ModuleLowPwr state, due to LowPower mode implementation restrictions. See 
     * Table8-19 for the management function groups that may be restricted for that reason. Note: Because restrictions 
     * areadvertised here, the encoding is somewhat unusual as follows: 0: management functionality fully supported 
     * (unrestricted)1: management functionality not fully supported (restricted) Note: The purpose of his 
     * advertisementis to provide full transparency to the host if a module can or cannot fully support certain 
     * non-trafficrelated but possibly power-hungry management functions, because the implementation would violate the 
     * powerdissipation constraint of Low Power mode. For management functions with result feedback (such as CDB 
     * commands)a host may also use a try-and-err approach to find out if the function is supported.
     */
    uint8_t LowPowerRestrictions;  /* r62 */
    uint8_t reserved_63[22];  /**< r63.. */
    /**
     * @brief MediaType
     * @details The MediaType field defines the interpretation of MediaInterfaceID values in the following Application 
     * Descriptors.See Table 8-20 for the MediaType encoding.
     * @access RO Rqd.
     */
    uint8_t MediaType;  /* r85 */
    /** @brief Application Descriptors (AppSel 1-8) */
    struct {
        /**
         * @brief HostInterfaceID
         * @details AppDescriptor1 AppSel 1 (0001b) See Table 8-22
         * @access RO Rqd.
         */
        uint8_t HostInterfaceID : 8;  /* r86.7-0 */
        /**
         * @brief MediaInterfaceID
         */
        uint8_t MediaInterfaceID : 8;  /* r87.7-0 */
        /**
         * @brief MediaLaneCount
         */
        uint8_t MediaLaneCount : 4;  /* r88.3-0 */
        /**
         * @brief HostLaneCount
         */
        uint8_t HostLaneCount : 4;  /* r88.7-4 */
        /**
         * @brief HostLaneAssignmentOptions
         */
        uint8_t HostLaneAssignmentOptions : 8;  /* r89.7-0 */
    } AppDescriptors[8];
    /**
     * @brief PasswordChangeEntryArea
     * @details U32: new password value
     * @access WO/SC Opt.
     */
    uint32_t PasswordChangeEntryArea;  /* r118 */
    /**
     * @brief PasswordEntryArea
     * @details U32: password value
     * @access WO/SC Opt.
     */
    uint32_t PasswordEntryArea;  /* r122 */
    /**
     * @brief BankSelect
     * @details Bank Index of Page mapped to Upper Memory (if applicable). The current BankSelect value determines 
     * whichBank of a Page is accessed (for Pages with Banking) when a host ACCESS addresses a Byte in Upper Memory 
     * (address128 through 255). Ignored when the Page indexed by PageSelect is unbanked.
     * @access RW Cnd.
     */
    uint8_t BankSelect;  /* r126 */
    /**
     * @brief PageSelect
     * @details Page Index of Page mapped to Upper Memory The current PageSelect value determines which Page (or Page 
     * ina Bank) is accessed when a host ACCESS addresses a Byte in Upper Memory (address 128 through 255) Note: The 
     * modulewill clear the PageSelect when needed to prevent mapping an unsupported page.
     * @access RWW Cnd.
     */
    uint8_t PageSelect;  /* r127 */

} cmis_low_memory_t;

#if __STDC_VERSION__ >= 202311L
static_assert(sizeof(cmis_low_memory_t) == 128, "cmis_low_memory_t must be exactly 128 bytes");
#elif __STDC_VERSION__ >= 201112L
_Static_assert(sizeof(cmis_low_memory_t) == 128, "cmis_low_memory_t must be exactly 128 bytes");
#elif defined(__GNUC__) || defined(__clang__)
_Static_assert(sizeof(cmis_low_memory_t) == 128, "cmis_low_memory_t must be exactly 128 bytes");
#else
/* verify manually: sizeof(cmis_low_memory_t) must be 128 */
#endif

#endif  // __CMIS_LOW_MEMORY_H