/* Auto-generated by CMIS2C - CMIS Page 01h Register Map */
#ifndef __CMIS_PAGE_01H_H
#define __CMIS_PAGE_01H_H

#include <stdint.h>

/** @brief CMIS Page 01h Register Map (Bytes 128-255) */
typedef struct __attribute__((packed)) {

    /**
     * @brief ModuleInactiveFirmwareMajorRevision
     * @details U8 Numeric representation of module inactive firmware major revision
     * @access RO Rqd.
     */
    uint8_t ModuleInactiveFirmwareMajorRevision;  /* r128 */
    /**
     * @brief ModuleInactiveFirmwareMinorRevision
     * @details U8 Numeric representation of module inactive firmware minor revision
     * @access RO Rqd.
     */
    uint8_t ModuleInactiveFirmwareMinorRevision;  /* r129 */
    /**
     * @brief ModuleHardwareMajorRevision
     * @details U8 Numeric representation of module hardware major revision
     * @access RO Rqd.
     */
    uint8_t ModuleHardwareMajorRevision;  /* r130 */
    /**
     * @brief ModuleHardwareMinorRevision
     * @details U8 Numeric representation of module hardware minor revision
     * @access RO Rqd.
     */
    uint8_t ModuleHardwareMinorRevision;  /* r131 */
        /**
         * @brief BaseLengthSMF
         * @details Base link length for SMF fiber in km. Must be multiplied by multiplier defined in bits 7-6 to 
         * calculateactual link length.
         * @access RO Rqd.
         */
        /**
         * @brief LengthMultiplierSMF
         * @details Link length multiplier for SMF fiber 00: 0.1 (0.1 to 6.3 km) 01: 1 (1 to 63 km) 10: 10 (10 to 630 
         * km)11: multiplier is specified in 01h:137
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t BaseLengthSMF : 6;  /* r132.5-0 */
            uint8_t LengthMultiplierSMF : 2;  /* r132.7-6 */
        };
        uint8_t r132;
    };
    /**
     * @brief LengthOM5
     * @details Link length supported for OM5 fiber, units of 2 m (2 to 510 m)
     * @access RO Rqd.
     */
    uint8_t LengthOM5;  /* r133 */
    /**
     * @brief LengthOM4
     * @details Link length supported for OM4 fiber, units of 2 m (2 to 510 m)
     * @access RO Rqd.
     */
    uint8_t LengthOM4;  /* r134 */
    /**
     * @brief LengthOM3
     * @details Link length supported for EBW 50/125 µm fiber (OM3), units of 2m (2 to 510 m)
     * @access RO Rqd.
     */
    uint8_t LengthOM3;  /* r135 */
    /**
     * @brief LengthOM2
     * @details Link length supported for 50/125 µm fiber (OM2), units of 1m (1 to 255 m)
     * @access RO Rqd.
     */
    uint8_t LengthOM2;  /* r136 */
        /**
         * @brief LengthMultiplierSMF2
         * @details Link length multiplier for SMF fiber (if 01h:132 = 11) 00: 50 (50 to 3150 km) 01: 100 (100 to 6300 
         * km)10: 200 (200 to 12600 km) 11: 500 (500 to 31500 km)
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t _pad_137_0 : 6;
            uint8_t LengthMultiplierSMF2 : 2;  /* r137.7-6 */
        };
        uint8_t r137;
    };
    /**
     * @brief NominalWavelength
     * @details U16 nominal transmitter output wavelength for a single wavelength module at room temperature in units 
     * of0.05nm
     * @access RO Cnd.
     */
    uint16_t NominalWavelength;  /* r138 */
    /**
     * @brief WavelengthTolerance
     * @details U16 wavelength tolerance tol as the worst case +/-tol range around the NominalWavelength under all 
     * normaloperating conditions in units of 0.005nm
     * @access RO Cnd.
     */
    uint16_t WavelengthTolerance;  /* r140 */
        /**
         * @brief BanksSupported
         * @details Banks supported for those Pages in range 10h-2Fh that are lane-banked by groups of 8 lanes 00b: 
         * Bank0 supported (8 lanes) 01b: Banks 0 and 1 supported (16 lanes) 10b: Banks 0-3 supported (32 lanes) 1 1b: 
         * reserved
         */
        /**
         * @brief Page03hSupported
         * @details User Page 03h supported
         */
        /**
         * @brief CmisFfSupported
         * @details Form Factor specific functionality as specified in the CMIS-FF supplement [8] is supported on Page 
         * 05h.
         */
        /**
         * @brief CoherentPagesSupported
         * @details Banked Pages 30h-4Fh (partially) supported (advertisement details are specified in [7])
         */
        /**
         * @brief DiagnosticPagesSupported
         * @details Banked Pages 13h-14h supported
         */
        /**
         * @brief VDMPagesSupported
         * @details VDM Pages 20h-2Fh (partially) supported (advertisement details in Page 2Fh)
         */
        /**
         * @brief NetworkPathPagesSupported
         * @details Page 16h and NP-related parts of Page 17h supported
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t BanksSupported : 2;  /* r142.1-0 */
            uint8_t Page03hSupported : 1;  /* r142.2 */
            uint8_t CmisFfSupported : 1;  /* r142.3 */
            uint8_t CoherentPagesSupported : 1;  /* r142.4 */
            uint8_t DiagnosticPagesSupported : 1;  /* r142.5 */
            uint8_t VDMPagesSupported : 1;  /* r142.6 */
            uint8_t NetworkPathPagesSupported : 1;  /* r142.7 */
        };
        uint8_t r142;
    };
        /**
         * @brief ModSelWaitTimeMantissa_m
         */
        /**
         * @brief ModSelWaitTimeExponent_e
         * @details ModSelWaitTime value represented as m∙2e in μs 00h: no data available
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t ModSelWaitTimeMantissa_m : 5;  /* r143.4-0 */
            uint8_t ModSelWaitTimeExponent_e : 3;  /* r143.7-5 */
        };
        uint8_t r143;
    };
        /**
         * @brief MaxDurationDPInit
         * @details Maximum duration of the DPInit state (encoded as per Table 8-48)
         */
        /**
         * @brief MaxDurationDPDeinit
         * @details Maximum duration of the DPDeinit state (encoded as per Table 8-48)
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t MaxDurationDPInit : 4;  /* r144.3-0 */
            uint8_t MaxDurationDPDeinit : 4;  /* r144.7-4 */
        };
        uint8_t r144;
    };
        /**
         * @brief Aux1MonObservable
         * @details 0b: Aux 1 monitor is custom 1b: Aux 1 monitor monitors TEC current
         * @access RO Adv.
         */
        /**
         * @brief Aux2MonObservable
         * @details 0b: Aux 2 monitor monitors Laser Temperature 1b: Aux 2 monitor monitors TEC current
         * @access RO Adv.
         */
        /**
         * @brief Aux3MonObservable
         * @details 0b: Aux 3 monitor monitors Laser Temperature 1b: Aux 3 monitor monitors Vcc2
         * @access RO Adv.
         */
        /**
         * @brief TimingPage15hSupported
         * @details 0b: Timing characteristics (Page 15h) not supported 1b: Timing characteristics (Page 15h) supported
         * @access RO Rqd.
         */
        /**
         * @brief ePPSSupported
         * @details Support of the Enhanced Pulse Per Second timing signal [2] 0b/1b: ePPS signal processing not 
         * supported/supported
         * @access RO Rqd.
         */
        /**
         * @brief TxInputClockingCapabilities
         * @details Defines which Tx input lanes must be frequency synchronous 00b: Tx input lanes 1-8 01b: Tx input 
         * lanes1-4 and 5-8 10b: Tx input lanes 1-2, 3-4, 5-6, 7-8 11b: Lanes may be asynchronous in frequency When 
         * morethan 8 lanes are supported, the above grouping applies to each group of 8 lanes (each Bank)
         * @access RO Rqd.
         */
        /**
         * @brief CoolingImplemented
         * @details 0b: Uncooled transmitter device 1b: Cooled transmitter
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t Aux1MonObservable : 1;  /* r145.0 */
            uint8_t Aux2MonObservable : 1;  /* r145.1 */
            uint8_t Aux3MonObservable : 1;  /* r145.2 */
            uint8_t TimingPage15hSupported : 1;  /* r145.3 */
            uint8_t ePPSSupported : 1;  /* r145.4 */
            uint8_t TxInputClockingCapabilities : 2;  /* r145.6-5 */
            uint8_t CoolingImplemented : 1;  /* r145.7 */
        };
        uint8_t r145;
    };
    /**
     * @brief ModuleTempMax
     * @details S8 Maximum allowed module temperature in 1 deg C increments. ModuleTempMax = ModuleTempMin = 0 
     * indicates‘not specified’.
     * @access RO Cnd.
     */
    uint8_t ModuleTempMax;  /* r146 */
    /**
     * @brief ModuleTempMin
     * @details S8 Minimum allowed module temperature in 1 deg C increments. ModuleTempMax = ModuleTempMin = 0 
     * indicates‘not specified’.
     * @access RO Cnd.
     */
    uint8_t ModuleTempMin;  /* r147 */
    /**
     * @brief PropagationDelay
     * @details U16 Propagation delay of a non-separable AOC in multiples of 10 ns rounded to the nearest 10 ns, or 
     * zerofor ‘not specified’.
     * @access RO Cnd.
     */
    uint16_t PropagationDelay;  /* r148 */
    /**
     * @brief OperatingVoltageMin
     * @details U8 Minimum supported module operating voltage, in 20 mV increments (0-5.1 V), or zero for ‘not 
     * specified’.
     * @access RO Cnd.
     */
    uint8_t OperatingVoltageMin;  /* r150 */
        /**
         * @brief TxDisableIsModuleWide
         * @details 0b: Tx output disable is controlled per lane 1b: All Tx output lanes disabled when any 
         * OutputDisableTxset
         */
        /**
         * @brief TxDisableIsFast
         * @details 0b: Module responds to Tx Output Disable with regular timing 1b: Module responds to Tx Output 
         * Disablein “fast mode” timing limits Refer to form factor hardware specification for regular and “fast mode” 
         * timinglimit requirements
         */
        /**
         * @brief RxLOSIsFast
         * @details 0b: Module raises Rx LOS within regular timing limits 1b: Module raises Rx LOS within “fast mode” 
         * timinglimits Refer to form factor hardware specification for regular and “fast mode” timing limit 
         * requirements
         */
        /**
         * @brief RxLOSType
         * @details 0b: Rx LOS responds to OMA 1b: Rx LOS responds to P av Note: LOS Type depends on interface 
         * standardssupported
         */
        /**
         * @brief RxPowerMeasurementType
         * @details 0b: OMA 1b: average power
         */
        /**
         * @brief RxOutputEqType
         * @details 00b: Peak-to-peak (p-p) amplitude stays constant, or not implemented, or no information 01b: 
         * Steady-stateamplitude stays constant 10b: Average of p-p and steady-state amplitude stays constant 11b: 
         * Reserved
         */
        /**
         * @brief OpticalDetectorType
         * @details 0b: PIN detector 1b: APD detector
         * @access RO R qd.
         */
    union {
        struct {
            uint8_t TxDisableIsModuleWide : 1;  /* r151.0 */
            uint8_t TxDisableIsFast : 1;  /* r151.1 */
            uint8_t RxLOSIsFast : 1;  /* r151.2 */
            uint8_t RxLOSType : 1;  /* r151.3 */
            uint8_t RxPowerMeasurementType : 1;  /* r151.4 */
            uint8_t RxOutputEqType : 2;  /* r151.6-5 */
            uint8_t OpticalDetectorType : 1;  /* r151.7 */
        };
        uint8_t r151;
    };
    /**
     * @brief CDRPowerSavedPerLane
     * @details U8 Minimum power consumption saved per CDR per lane when placed in CDR bypass, in multiples of 0.01 W 
     * roundedup to the next whole multiple of 0.01 W
     * @access RO Cnd.
     */
    uint8_t CDRPowerSavedPerLane;  /* r152 */
        /**
         * @brief TxInputEqMax
         * @details Maximum supported value of the Tx Input Equalization control for host-controlled equalizer 
         * operation(see section 6.2.5.1)
         */
        /**
         * @brief RxOutputLevel0Supported
         * @details 0b/1b: Amplitude Code 0 not supported/supported
         */
        /**
         * @brief RxOutputLevel1Supported
         * @details 0b/1b: Amplitude Code 1 not supported/supported
         */
        /**
         * @brief RxOutputLevel2Supported
         * @details 0b/1b: Amplitude Code 2 not supported/supported
         */
        /**
         * @brief RxOutputLevel3Supported
         * @details 0b/1b: Amplitude Code 3 not supported/supported
         * @access RO Cnd.
         */
    union {
        struct {
            uint8_t TxInputEqMax : 4;  /* r153.3-0 */
            uint8_t RxOutputLevel0Supported : 1;  /* r153.4 */
            uint8_t RxOutputLevel1Supported : 1;  /* r153.5 */
            uint8_t RxOutputLevel2Supported : 1;  /* r153.6 */
            uint8_t RxOutputLevel3Supported : 1;  /* r153.7 */
        };
        uint8_t r153;
    };
        /**
         * @brief RxOutputEqPreCursorMax
         * @details Maximum supported value of the Rx Output Eq Pre-cursor control (see section 6.2.5.2)
         */
        /**
         * @brief RxOutputEqPostCursorMax
         * @details Maximum supported value of the Rx Output Eq Post-cursor control (see section 6.2.5.2)
         * @access RO Cnd.
         */
    union {
        struct {
            uint8_t RxOutputEqPreCursorMax : 4;  /* r154.3-0 */
            uint8_t RxOutputEqPostCursorMax : 4;  /* r154.7-4 */
        };
        uint8_t r154;
    };
        /**
         * @brief InputPolarityFlipTxSupported
         * @details 0b/1b: InputPolarityFlipTx control not supported/supported
         */
        /**
         * @brief OutputDisableTxSupported
         * @details 0b/1b: Host cannot/can disable Tx outputs using the OutputDisableTx register
         */
        /**
         * @brief AutoSquelchDisableTxSupported
         * @details 0b/1b: Host cannot/can disable automatic squelching of Tx outputs using AutoSquelchDisableTx*
         */
        /**
         * @brief ForcedSquelchTxSupported
         * @details 0b/1b: Host cannot/can force squelching of Tx outputs using OutputSquelchForceTx*
         */
        /**
         * @brief SquelchMethodTx
         * @details 00b: Tx output squelching function is not supported 01b: Tx output squelching function reduces OMA 
         * 10b:Tx output squelching function reduces P av 11b: Host controls the method for Tx output squelching, 
         * reducingOMA or P (see Table 8-11) av Note: Support of the Tx output squelching function implies support of 
         * automaticTx squelching control
         */
        /**
         * @brief TransmitterIsTunable
         * @details 0b: Transmitter not tunable 1b: Transmitter is tunable (Pages 04h & 12h supported)
         */
        /**
         * @brief WavelengthIsControllable
         * @details 0b: No wavelength control 1b: Active wavelength control supported Note: Active Control does not 
         * implytunability
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t InputPolarityFlipTxSupported : 1;  /* r155.0 */
            uint8_t OutputDisableTxSupported : 1;  /* r155.1 */
            uint8_t AutoSquelchDisableTxSupported : 1;  /* r155.2 */
            uint8_t ForcedSquelchTxSupported : 1;  /* r155.3 */
            uint8_t SquelchMethodTx : 2;  /* r155.5-4 */
            uint8_t TransmitterIsTunable : 1;  /* r155.6 */
            uint8_t WavelengthIsControllable : 1;  /* r155.7 */
        };
        uint8_t r155;
    };
        /**
         * @brief OutputPolarityFlipRxSupported
         * @details 0b/1b: PolarityFlipRx not supported/supported
         */
        /**
         * @brief OutputDisableRxSupported
         * @details 0b/1b: Host cannot/can disable Rx outputs using the OutputDisableRx register
         */
        /**
         * @brief AutoSquelchDisableRxSupported
         * @details 0b/1b: Host cannot/can disable automatic squelching of Rx outputs using the AutoSquelchDisableRx 
         * registerNote: Rx squelching and automatic Rx squelching control is not advertised and always assumed to be 
         * supported.
         */
        /**
         * @brief BankBroadcastSupported
         * @details 0b/1b: The BankBroadcastEnable control is not supported/supported
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t OutputPolarityFlipRxSupported : 1;  /* r156.0 */
            uint8_t OutputDisableRxSupported : 1;  /* r156.1 */
            uint8_t AutoSquelchDisableRxSupported : 1;  /* r156.2 */
            uint8_t _pad_156_3 : 4;
            uint8_t BankBroadcastSupported : 1;  /* r156.7 */
        };
        uint8_t r156;
    };
        /**
         * @brief FailureFlagTxSupported
         * @details 0b: Tx Fault Flags not supported 1b: supported
         */
        /**
         * @brief LOSFlagTxSupported
         * @details 0b: Tx Loss of Signal Flags not supported 1b: supported
         */
        /**
         * @brief CDRLOLFlagTxSupported
         * @details 0b: Tx CDR Loss of Lock Flags not supported 1b: supported
         */
        /**
         * @brief AdaptiveInputEqFailFlagTxSupported
         * @details 0b: Tx Adaptive Input Eq Fail Flags not supported 1b: supported
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t FailureFlagTxSupported : 1;  /* r157.0 */
            uint8_t LOSFlagTxSupported : 1;  /* r157.1 */
            uint8_t CDRLOLFlagTxSupported : 1;  /* r157.2 */
            uint8_t AdaptiveInputEqFailFlagTxSupported : 1;  /* r157.3 */
            uint8_t _pad_157_4 : 4;
        };
        uint8_t r157;
    };
        /**
         * @brief LOSFlagRxSupported
         * @details 0b: Rx Loss of Signal Flags not supported 1b: Rx Loss of Signal Flags supported
         */
        /**
         * @brief CDRLOLFlagRxSupported
         * @details 0b: Rx CDR Loss of Lock Flags not supported 1b: Rx CDR Loss of Lock Flags supported
         * @access RO R qd.
         */
    union {
        struct {
            uint8_t _pad_158_0 : 1;
            uint8_t LOSFlagRxSupported : 1;  /* r158.1 */
            uint8_t CDRLOLFlagRxSupported : 1;  /* r158.2 */
            uint8_t _pad_158_3 : 5;
        };
        uint8_t r158;
    };
        /**
         * @brief TempMonSupported
         * @details 0b: Temperature monitor not supported 1b: Temperature monitor supported
         */
        /**
         * @brief VccMonSupported
         * @details 0b: Internal 3.3 V monitor not supported 1b: Internal 3.3 V monitor supported
         */
        /**
         * @brief Aux1MonSupported
         * @details 0b: Aux 1 monitor not supported 1b: Aux 1 monitor supported
         */
        /**
         * @brief Aux2MonSupported
         * @details 0b: Aux 2 monitor not supported 1b: Aux 2 monitor supported
         */
        /**
         * @brief Aux3MonSupported
         * @details 0b: Aux 3 monitor not supported 1b: Aux 3 monitor supported
         */
        /**
         * @brief CustomMonSupported
         * @details 0b: Custom monitor not supported 1b: Custom monitor supported
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t TempMonSupported : 1;  /* r159.0 */
            uint8_t VccMonSupported : 1;  /* r159.1 */
            uint8_t Aux1MonSupported : 1;  /* r159.2 */
            uint8_t Aux2MonSupported : 1;  /* r159.3 */
            uint8_t Aux3MonSupported : 1;  /* r159.4 */
            uint8_t CustomMonSupported : 1;  /* r159.5 */
            uint8_t _pad_159_6 : 2;
        };
        uint8_t r159;
    };
        /**
         * @brief TxBiasMonSupported
         * @details 0b: Tx Bias monitor not supported 1b: Tx Bias monitor supported
         */
        /**
         * @brief TxOpticalPowerMonSupported
         * @details 0b: Tx Output Optical Power monitor not supported 1b: Tx Output Optical Power monitor supported
         */
        /**
         * @brief RxOpticalPowerMonSupported
         * @details 0b: Rx Optical Input Power monitor not supported 1b: Rx Optical Input Power monitor supported
         */
        /**
         * @brief TxBiasCurrentScalingFactor
         * @details Multiplier for 2uA Bias current increment used in Tx Bias current monitor and threshold registers 
         * (seeTable 8-63 and Table 8-89) 00b: multiply x1 01b: multiply x2 10b: multiply x4 11b: reserved
         */
    union {
        struct {
            uint8_t TxBiasMonSupported : 1;  /* r160.0 */
            uint8_t TxOpticalPowerMonSupported : 1;  /* r160.1 */
            uint8_t RxOpticalPowerMonSupported : 1;  /* r160.2 */
            uint8_t TxBiasCurrentScalingFactor : 2;  /* r160.4-3 */
            uint8_t _pad_160_5 : 3;
        };
        uint8_t r160;
    };
        /**
         * @brief TxCDRSupported
         * @details 0b/1b: Tx CDR not supported / supported
         */
        /**
         * @brief TxCDRBypassControlSupported
         * @details 0b: If a Tx CDR is supported, it cannot be bypassed 1b: If a Tx CDR is supported, it can be 
         * bypassed
         */
        /**
         * @brief TxInputEqHostControlSupported
         * @details 0b: host-control of Tx Input Eq target not supported 1b: host-control of Tx Input Eq target 
         * supported
         */
        /**
         * @brief TxInputAdaptiveEqSupported
         * @details 0b/1b: Adaptive Tx Input Eq not supported / supported
         */
        /**
         * @brief TxInputEqFreezeSupported
         * @details 0b/1b: Tx Input Eq Freeze not supported / supported
         */
        /**
         * @brief TxInputEqRecallBuffersSupported
         * @details 00b: Tx Input Eq Store/Recall not supported 01b: Tx Input Eq Store/Recall buffer count=1 10b: Tx 
         * InputEq Store/Recall buffer count=2 11b: reserved
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t TxCDRSupported : 1;  /* r161.0 */
            uint8_t TxCDRBypassControlSupported : 1;  /* r161.1 */
            uint8_t TxInputEqHostControlSupported : 1;  /* r161.2 */
            uint8_t TxInputAdaptiveEqSupported : 1;  /* r161.3 */
            uint8_t TxInputEqFreezeSupported : 1;  /* r161.4 */
            uint8_t TxInputEqRecallBuffersSupported : 2;  /* r161.6-5 */
            uint8_t _pad_161_7 : 1;
        };
        uint8_t r161;
    };
        /**
         * @brief RxCDRSupported
         * @details 0b: Rx CDR not supported 1b: Rx CDR supported
         */
        /**
         * @brief RxCDRBypassControlSupported
         * @details 0b: Rx CDR Bypass control not supported (if a CDR is supported, it cannot be bypassed) 1b: Rx CDR 
         * Bypasscontrol supported
         */
        /**
         * @brief RxOutputAmplitudeControlSup_ported
         * @details 0b: Rx Output Amplitude control not supported 1b: Rx Output Amplitude control supported
         */
        /**
         * @brief RxOutputEqControlSupported
         * @details Host control of Rx Output Eq targets 00b: not supported 01b: only Pre-cursor supported 10b: only 
         * Post-cursorsupported 11b: both Pre- and Post-cursor supported
         */
        /**
         * @brief StagedSet1Supported
         * @details Staged Control Set 1 supported on Page 10h
         */
        /**
         * @brief UnidirReconfigSupported
         * @details 0b/1b: ApplyImmediateTx/Rx on Page 10h and DPConfigTx/Rx on Page 19h are not supported / supported, 
         * forall supported Staged Control Sets
         * @access RO Rqd.
         */
        /**
         * @brief VersatileControlSetSupported
         * @details 0b/1b: CMIS-VCS [6] functionality is not supported / supported, for all supported Staged Control 
         * Sets.Note: See specifications in [6] if the VCS parameter space extensions on Pages 18h and 19h are 
         * supported.
         * @access RO
         */
    union {
        struct {
            uint8_t RxCDRSupported : 1;  /* r162.0 */
            uint8_t RxCDRBypassControlSupported : 1;  /* r162.1 */
            uint8_t RxOutputAmplitudeControlSup_ported : 1;  /* r162.2 */
            uint8_t RxOutputEqControlSupported : 2;  /* r162.4-3 */
            uint8_t StagedSet1Supported : 1;  /* r162.5 */
            uint8_t UnidirReconfigSupported : 1;  /* r162.6 */
            uint8_t VersatileControlSetSupported : 1;  /* r162.7 */
        };
        uint8_t r162;
    };
        /**
         * @brief CdbMaxPagesEPL
         * @details This field encodes the EPL Page range supported or, equivalently, the maximum length of extended 
         * payload:Value Supported Total Number of EPL Pages Pages EPL Bytes 0: (none) 0 0 1: A0h 1 128 2: A0h-A1h 2 
         * 2563 A0h-A2h 3 384 4 A0h-A3h 4 512 5 A0h-A7h 8 1024 6 A0h-Abh 12 1536 7 A0h-Afh 16 2048 Note: A host can 
         * accessall supported EPL Pages and the EPL Page range is sufficient for all supported CDB commands. The 
         * requirednumber of EPL pages may be CDB command specific.
         * @access RO Cnd.
         */
        /**
         * @brief CdbAutoPagingSupported
         * @details When the Management Memory current address pointer advances past the end of an Extended Payload 
         * (EPL)CDB Page (A0h-AFh), the page number in the PageSelect Byte will automatically increment and the Memory 
         * Mapcurrent address pointer automatically wraps to 128. When the last page number AFh is incremented, the 
         * pagenumber wraps back to A0h. 0b: Auto Paging not supported 1b: Auto Paging and Auto Page wrap supported
         * @access RO Cnd.
         */
        /**
         * @brief CdbBackgroundModeSupported
         * @details 0b: Background CDB operation not supported. 1b: Background CDB operation supported Note: In 
         * BackgroundMode, register access is possible while a CDB command is still being processed.
         * @access RO Cnd.
         */
        /**
         * @brief CdbInstancesSupported
         * @details 00b: CDB functionality not supported 01b: One CDB instance supported 10b: Two CDB instances 
         * supported11b: Reserved One CDB Instance Bank 0 of Pages 9Fh and the subset of Pages A0h-Afh advertised in 
         * CdbMaxPagesEPL(01h:163.3-0), CdbCmdCompleteFlag1 Flag (00h:8.6) and the associated Mask (00h:31.6) are 
         * supported.Two CDB Instances Banks 0 and 1 of Pages 9Fh and of the subset of Pages A0h-Afh advertised in 
         * CdbMaxPagesEPL(01h:163.3-0), CdbCmdCompleteFlag<i> (00h:8.7-6), <i> = 1,2, and the associated Masks 
         * (00h:31.7-6)are supported.
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t CdbMaxPagesEPL : 4;  /* r163.3-0 */
            uint8_t CdbAutoPagingSupported : 1;  /* r163.4 */
            uint8_t CdbBackgroundModeSupported : 1;  /* r163.5 */
            uint8_t CdbInstancesSupported : 2;  /* r163.7-6 */
        };
        uint8_t r163;
    };
    /**
     * @brief CdbReadWriteLengthExtension
     * @details Note: For READ and WRITE efficiency in CDB messaging, a module can support multi-byte ACCESS in the CDB 
     * Pagerange (9Fh-Afh) with more than 8 bytes. CdbReadWriteLengthExtension = i specifies i*8 allowable additional 
     * numberof bytes in a WRITE or READ
     * @access RO Cnd.
     */
    uint8_t CdbReadWriteLengthExtension;  /* r164 */
        /**
         * @brief CdbExtMaxBusyTime
         * @details When CdbMaxBusySpecMethod=1b: CdbExtMaxBusyTime = X encodes the maximum CDB busy time T CDBB 
         * asmax(1,X)*160ms in a range of 160 ms to 4960 ms. When CdbMaxBusySpecMethod=0b: don’t care
         * @access RO Cnd.
         */
        /**
         * @brief CdbCommandTriggerMethod
         * @details Determines how the host triggers CDB command processing in the module and when this occurs: 1b: 
         * whenthe MCI transaction of a WRITE access including the CMDID register 9Fh:129 is properly terminated by the 
         * host(STOP). 0b: when a single byte WRITE to 9Fh:129 or a two-byte WRITE to the CMDID register Byte 
         * 9Fh:128-129is properly terminated by the host (STOP). Note: Preferred method 1b enables the host to WRITE a 
         * completeCMD message (header and body) in one go, whereas in Method 0b the host composes the CMD message body 
         * firstand then triggers CMD processing in a second step. See also section 7.2.
         * @access RO Cnd.
         */
    union {
        struct {
            uint8_t CdbExtMaxBusyTime : 5;  /* r165.4-0 */
            uint8_t _pad_165_5 : 2;
            uint8_t CdbCommandTriggerMethod : 1;  /* r165.7 */
        };
        uint8_t r165;
    };
        /**
         * @brief CdbMaxBusyTime
         * @details When CdbMaxBusySpecMethod=0b: CdbMaxBusyTime=X encodes the maximum CDB busy time T as (80– CDBB 
         * min(80,X))msin a range of 0 ms to 80 ms. When CdbMaxBusySpecMethod=1b: don’t care
         * @access RO Cnd.
         */
        /**
         * @brief CdbMaxBusySpecMethod
         * @details 0b: Indicates that the maximum CDB busy time T is CDBB specified via CdbMaxBusyTime (01h:166.6-0) 
         * 1b:Indicates that the maximum CDB busy time T is CDBB specified via CdbExtMaxBusyTime (01h:165.4-0).
         * @access RO Cnd.
         */
    union {
        struct {
            uint8_t CdbMaxBusyTime : 7;  /* r166.6-0 */
            uint8_t CdbMaxBusySpecMethod : 1;  /* r166.7 */
        };
        uint8_t r166;
    };
        /**
         * @brief MaxDurationModulePwrUp
         * @details Encoded maximum duration of the ModulePwrUp state (see Table 8-48)
         */
        /**
         * @brief MaxDurationModulePwrDn
         * @details Encoded maximum duration of the ModulePwrDn state (see Table 8-48)
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t MaxDurationModulePwrUp : 4;  /* r167.3-0 */
            uint8_t MaxDurationModulePwrDn : 4;  /* r167.7-4 */
        };
        uint8_t r167;
    };
        /**
         * @brief MaxDurationDPTxTurnOn
         * @details Encoded maximum duration of the DPTxTurnOn state (see Table 8-48)
         */
        /**
         * @brief MaxDurationDPTxTurnOff
         * @details Encoded maximum duration of the DPTxTurnOff state (see Table 8-48)
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t MaxDurationDPTxTurnOn : 4;  /* r168.3-0 */
            uint8_t MaxDurationDPTxTurnOff : 4;  /* r168.7-4 */
        };
        uint8_t r168;
    };
        /**
         * @brief MaxDurationBPC
         * @details U4: Encoded scaling of the maximum ACCESS hold-off duration tBPC, after a PageMapping register 
         * change(see Table 10-4). The maximum bank or page switch time given MaxDurationBPC = i is tBPC / 2i
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t MaxDurationBPC : 4;  /* r169.3-0 */
            uint8_t _pad_169_4 : 4;
        };
        uint8_t r169;
    };
    uint8_t reserved_170[5];  /**< r170.. */
        /**
         * @brief NADBanksSupported
         * @details 0: Normalized Application Descriptors not supported n>0: Normalized Application Descriptors 
         * supportedon n Banks of Page 1Ch. Up to n∙15 Applications can be advertised in n groups of 15 NADs each.
         */
    union {
        struct {
            uint8_t NADBanksSupported : 4;  /* r175.3-0 */
            uint8_t _pad_175_4 : 4;
        };
        uint8_t r175;
    };
    /** @brief Media Lane Assignment Options (App 1-15) */
    uint8_t MediaLaneAssignmentOptions[15];
    uint8_t reserved_191[32];  /**< r191.. */
    /** @brief Application Descriptors (AppSel 9-15) */
    struct {
        /**
         * @brief HostInterfaceID
         * @details AppDescriptor9 AppSel 9 (1001b) See Table 8-22
         * @access RO Cnd.
         */
        uint8_t HostInterfaceID : 8;  /* r223.7-0 */
        /**
         * @brief MediaInterfaceID
         */
        uint8_t MediaInterfaceID : 8;  /* r224.7-0 */
        /**
         * @brief MediaLaneCount
         */
        uint8_t MediaLaneCount : 4;  /* r225.3-0 */
        /**
         * @brief HostLaneCount
         */
        uint8_t HostLaneCount : 4;  /* r225.7-4 */
        /**
         * @brief HostLaneAssignmentOptions
         */
        uint8_t HostLaneAssignmentOptions : 8;  /* r226.7-0 */
    } AppDescriptors[7];
        /**
         * @brief FullPageReadSupported
         * @details When supported, the maximum number of bytes that can be read with a READ access is 128. 00: unknown 
         * (onlyfor CMIS 5.2 or earlier) 01: not supported 02: supported (recommended since CMIS 5.3) Note: Support may 
         * becomemandatory in a future major CMIS revision
         */
        /**
         * @brief PasswordEntryResultSupported
         * @details 00: unknown (only for CMIS 5.2 or earlier) 01: not supported 02: supported
         */
        /**
         * @brief PasswordEntrySupported
         * @details 00: unknown (only for CMIS 5.2 or earlier) 01: not supported 02: supported
         */
        /**
         * @brief ScratchPadSupported
         * @details Host Scratchpad Area (13h:184-191) support: 00: unknown (only for CMIS 5.2 or earlier) 01: not 
         * supported02: supported (recommended since CMIS 5.3) Note: Support may become mandatory in a future major 
         * CMISrevision
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t FullPageReadSupported : 2;  /* r251.1-0 */
            uint8_t PasswordEntryResultSupported : 2;  /* r251.3-2 */
            uint8_t PasswordEntrySupported : 2;  /* r251.5-4 */
            uint8_t ScratchPadSupported : 2;  /* r251.7-6 */
        };
        uint8_t r251;
    };
        /**
         * @brief LinkTrainingSupported
         * @details 0b/1b: Functionality specified in CMIS-LT [9] is not supported / supported on Pages 50h-53h. Note: 
         * CMIS-LT-specificadvertisements may be found on these pages.
         */
        /**
         * @brief HostLaneSwitchingSupported
         * @details 0b/1b: Page 1Dh is not supported / supported
         */
    union {
        struct {
            uint8_t _pad_252_0 : 6;
            uint8_t LinkTrainingSupported : 1;  /* r252.6 */
            uint8_t HostLaneSwitchingSupported : 1;  /* r252.7 */
        };
        uint8_t r252;
    };
    uint8_t reserved_253[2];  /**< r253.. */
    /**
     * @brief Page_Checksum
     * @details Page Checksum of bytes 130-2541
     */
    uint8_t Page_Checksum;  /* r255 */

} cmis_page_01h_t;

#if __STDC_VERSION__ >= 202311L
static_assert(sizeof(cmis_page_01h_t) == 128, "cmis_page_01h_t must be exactly 128 bytes");
#elif __STDC_VERSION__ >= 201112L
_Static_assert(sizeof(cmis_page_01h_t) == 128, "cmis_page_01h_t must be exactly 128 bytes");
#elif defined(__GNUC__) || defined(__clang__)
_Static_assert(sizeof(cmis_page_01h_t) == 128, "cmis_page_01h_t must be exactly 128 bytes");
#else
/* verify manually: sizeof(cmis_page_01h_t) must be 128 */
#endif

#endif  // __CMIS_PAGE_01H_H