/* Auto-generated by CMIS2C - CMIS Page 00h Register Map */
#ifndef __CMIS_PAGE_00H_H
#define __CMIS_PAGE_00H_H

#include <stdint.h>

/** @brief CMIS Page 00h Register Map (Bytes 128-255) */
typedef struct __attribute__((packed)) {

    /**
     * @brief SFF8024Identifier
     * @details This Byte shall contain the same value as the SFF8024 Identifier Byte 00h:0. See Byte 00h:0 for a 
     * descriptionof its meaning.
     * @access RO Rqd.
     */
    uint8_t SFF8024Identifier;  /* r128 */
    /**
     * @brief VendorName
     * @details Vendor name (ASCII)
     */
    uint8_t VendorName[16];  /* r129 */
    /**
     * @brief VendorOUI
     * @details Vendor IEEE company ID
     */
    uint8_t VendorOUI[3];  /* r145 */
    /**
     * @brief VendorPN
     * @details Part number provided by vendor (ASCII)
     */
    uint8_t VendorPN[16];  /* r148 */
    /**
     * @brief VendorRev
     * @details Revision level for part number provided by vendor (ASCII)
     */
    uint16_t VendorRev;  /* r164 */
    /**
     * @brief VendorSN
     * @details Vendor Serial Number (ASCII)
     */
    uint8_t VendorSN[16];  /* r166 */
    /**
     * @brief Year
     * @details ASCII two low order digits of year (00=2000)
     * @access RO Rqd.
     */
    uint16_t Year;  /* r182 */
    /**
     * @brief Month
     * @details ASCII digits of month (01=Jan through 12=Dec)
     * @access RO Rqd.
     */
    uint16_t Month;  /* r184 */
    /**
     * @brief DayOfMonth
     * @details ASCII day of month (01-31)
     * @access RO Rqd.
     */
    uint16_t DayOfMonth;  /* r186 */
    /**
     * @brief LotCode
     * @details ASCII custom lot code, may be blank
     * @access RO Opt.
     */
    uint16_t LotCode;  /* r188 */
    /**
     * @brief CLEICode
     * @details Common Language Equipment Identification Code (ASCII)
     */
    uint8_t CLEICode[10];  /* r190 */
        /**
         * @brief ModulePowerClass1
         * @details 000: Power class 1 001: Power class 2 010: Power class 3 011: Power class 4 100: Power class 5 101: 
         * Powerclass 6 110: Power class 7 111: Power class 8
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t _pad_200_0 : 5;
            uint8_t ModulePowerClass1 : 3;  /* r200.7-5 */
        };
        uint8_t r200;
    };
    /**
     * @brief MaxPower
     * @details Maximum power consumption in multiples of 0.25 W rounded up to the next whole multiple of 0.25 W
     * @access RO Rqd.
     */
    uint8_t MaxPower;  /* r201 */
        /**
         * @brief BaseLength
         * @details Link length base value in meters. To calculate actual link length use multiplier in bits 7-6. A 
         * valueof 0 indicates an undefined Link Length, e.g. when the physical media can be disconnected from the 
         * module.
         */
        /**
         * @brief LengthMultiplier
         * @details Multiplier for value in bits 5-0: 00: multiplier 0.1 01: multiplier 1 10: multiplier 10 11: 
         * multiplier100
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t BaseLength : 6;  /* r202.5-0 */
            uint8_t LengthMultiplier : 2;  /* r202.7-6 */
        };
        uint8_t r202;
    };
    /**
     * @brief ConnectorType
     * @details Connector type of the media interface
     */
    uint8_t ConnectorType;  /* r203 */
    /**
     * @brief AttenuationAt5GHz
     * @details U8 cable attenuation at 5 GHz in 1 dB increments
     * @access RO Cnd.
     */
    uint8_t AttenuationAt5GHz;  /* r204 */
    /**
     * @brief AttenuationAt7GHz
     * @details U8 cable attenuation at 7 GHz in 1 dB increments
     * @access RO Cnd.
     */
    uint8_t AttenuationAt7GHz;  /* r205 */
    /**
     * @brief AttenuationAt12p9GHz
     * @details U8 cable attenuation at 12.9 GHz in 1 dB increments
     * @access RO Cnd.
     */
    uint8_t AttenuationAt12p9GHz;  /* r206 */
    /**
     * @brief AttenuationAt25p8GHz
     * @details U8 cable attenuation at 25.8 GHz in 1 dB increments
     * @access RO Cnd.
     */
    uint8_t AttenuationAt25p8GHz;  /* r207 */
    /**
     * @brief AttenuationAt53p1GHz
     * @details U8 cable attenuation at 53.125 GHz in 1 dB increments. A value of 0 dB indicates that this 
     * characteristicis not available (not relevant or otherwise unknown)
     * @access RO Cnd.
     */
    uint8_t AttenuationAt53p1GHz;  /* r208 */
    uint8_t reserved_209;  /**< r209 Reserved */
        /**
         * @brief MediaLaneUnsupportedLane1
         */
        /**
         * @brief MediaLaneUnsupportedLane2
         */
        /**
         * @brief MediaLaneUnsupportedLane3
         */
        /**
         * @brief MediaLaneUnsupportedLane4
         */
        /**
         * @brief MediaLaneUnsupportedLane5
         */
        /**
         * @brief MediaLaneUnsupportedLane6
         */
        /**
         * @brief MediaLaneUnsupportedLane7
         */
        /**
         * @brief MediaLaneUnsupportedLane8
         * @details Bool: MediaLaneUnsupportedLane<i> 0b: Media Lane <i> supported 1b: Media Lane <i> not supported 
         * Condition:Module supports at most 8 host lanes. Otherwise, byte is reserved (0 valued). Hosts should ignore 
         * thisbyte when the m odule supports more than 8 host lanes.
         * @access RO Cnd.
         */
    union {
        struct {
            uint8_t MediaLaneUnsupportedLane1 : 1;  /* r210.0 */
            uint8_t MediaLaneUnsupportedLane2 : 1;  /* r210.1 */
            uint8_t MediaLaneUnsupportedLane3 : 1;  /* r210.2 */
            uint8_t MediaLaneUnsupportedLane4 : 1;  /* r210.3 */
            uint8_t MediaLaneUnsupportedLane5 : 1;  /* r210.4 */
            uint8_t MediaLaneUnsupportedLane6 : 1;  /* r210.5 */
            uint8_t MediaLaneUnsupportedLane7 : 1;  /* r210.6 */
            uint8_t MediaLaneUnsupportedLane8 : 1;  /* r210.7 */
        };
        uint8_t r210;
    };
        /**
         * @brief FarEndConfiguration
         * @details Configuration of the far end module breakout. See Table 8-38 for configuration codes
         * @access RO Cnd.
         */
    union {
        struct {
            uint8_t FarEndConfiguration : 5;  /* r211.4-0 */
            uint8_t _pad_211_5 : 3;
        };
        uint8_t r211;
    };
    /**
     * @brief MediaInterfaceTechnology
     * @details Information on media side device or cable technology
     */
    uint8_t MediaInterfaceTechnology;  /* r212 */
        /**
         * @brief MciFlowControlDuration
         * @details Used by both host and module to compute the number 𝑵 of dummy bytes sent by the host during the 
         * FlowControl phase, in encoding dependent manner: MciFlowControlDurationEncoding static: 
         * 𝑵=2+𝑀𝑐𝑖𝐹𝑙𝑜𝑤𝐶𝑜𝑛𝑡𝑟𝑜𝑙𝐷𝑢𝑟𝑎𝑡𝑖𝑜𝑛MciFlowControlDurationEncoding speed-dependent: 𝐷 =0.2𝜇𝑠⋅𝑀𝑐𝑖𝐹𝑙𝑜𝑤𝐶𝑜𝑛𝑡𝑟𝑜𝑙𝐷𝑢𝑟𝑎𝑡𝑖𝑜𝑛 
         * 𝑵=max(2,𝑐𝑒𝑖𝑙(𝐷⋅𝑆𝑝𝑖𝑆𝑝𝑒𝑒𝑑𝐼𝑛𝑀𝐻𝑧/8)) where the ‘ceiling’ function 𝑐𝑒𝑖𝑙(.) returns the smallest integer that is 
         * notsmaller than its argument and where the SPI speed SpiSpeedInMHz is to be determined from decoding 
         * MciSpeedConfiguration(0h:27:3-0)
         * @access RO Cnd.
         */
        /**
         * @brief MciFlowControlDuration_Encoding
         * @details Defines the method to determine the duration of the Flow Control Phase 0b: static (given as number 
         * ofbytes) 1b: speed-dependent (given as a duration)
         * @access RO Cnd.
         */
    union {
        struct {
            uint8_t MciFlowControlDuration : 7;  /* r213.6-0 */
            uint8_t MciFlowControlDuration_Encoding : 1;  /* r213.7 */
        };
        uint8_t r213;
    };
    uint8_t reserved_214[7];  /**< r214.. */
    /**
     * @brief Custom
     * @details Custom [1]
     */
    uint8_t Custom;  /* r221 */
    /**
     * @brief PageChecksum
     * @details Page Checksum over bytes 128-221
     */
    uint8_t PageChecksum;  /* r222 */
    /**
     * @brief CustomInfoNV
     * @details Custom [33] Information (non-volatile)
     */
    uint8_t CustomInfoNV[33];  /* r223 */

} cmis_page_00h_t;

#if __STDC_VERSION__ >= 202311L
static_assert(sizeof(cmis_page_00h_t) == 128, "cmis_page_00h_t must be exactly 128 bytes");
#elif __STDC_VERSION__ >= 201112L
_Static_assert(sizeof(cmis_page_00h_t) == 128, "cmis_page_00h_t must be exactly 128 bytes");
#elif defined(__GNUC__) || defined(__clang__)
_Static_assert(sizeof(cmis_page_00h_t) == 128, "cmis_page_00h_t must be exactly 128 bytes");
#else
/* verify manually: sizeof(cmis_page_00h_t) must be 128 */
#endif

#endif  // __CMIS_PAGE_00H_H