"""CLI Entry Point."""

import click
import os
from .parser import extract_cmis_data, extract_page00h_data, extract_page01h_data
from .generator import generate_c_header, generate_page00h_header, generate_page01h_header

CMIS_UMBRELLA_H = """/* Auto-generated by CMIS2C - CMIS umbrella header */
#ifndef __CMIS_H
#define __CMIS_H

#include "cmis_low_memory.h"
#include "cmis_page_00h.h"
#include "cmis_page_01h.h"

#endif  // __CMIS_H
"""

@click.group()
def cli():
    """CMIS2C - Generate C header files from CMIS PDF."""
    pass

@cli.command()
@click.argument('pdf_path')
@click.option('-o', '--output-dir', default='.', help='Output directory for generated headers')
def generate(pdf_path, output_dir):
    """Parse CMIS PDF and generate C headers."""
    if not os.path.exists(pdf_path):
        click.echo(f"Error: File '{pdf_path}' not found.")
        return

    os.makedirs(output_dir, exist_ok=True)

    click.echo(f"Parsing {pdf_path}...")

    try:
        # Low memory (bytes 0-127)
        lm_regs = extract_cmis_data(pdf_path)
        click.echo(f"Low memory: {len(lm_regs)} register definitions.")
        lm_path = os.path.join(output_dir, "cmis_low_memory.h")
        if generate_c_header(lm_regs, lm_path):
            click.echo(f"  -> {lm_path}")
        else:
            click.echo("  Failed to generate cmis_low_memory.h")

        # Page 00h (bytes 128-255)
        p00h_regs = extract_page00h_data(pdf_path)
        click.echo(f"Page 00h: {len(p00h_regs)} register definitions.")
        p00h_path = os.path.join(output_dir, "cmis_page_00h.h")
        if generate_page00h_header(p00h_regs, p00h_path):
            click.echo(f"  -> {p00h_path}")
        else:
            click.echo("  Failed to generate cmis_page_00h.h")

        # Page 01h (bytes 128-255)
        p01h_regs = extract_page01h_data(pdf_path)
        click.echo(f"Page 01h: {len(p01h_regs)} register definitions.")
        p01h_path = os.path.join(output_dir, "cmis_page_01h.h")
        if generate_page01h_header(p01h_regs, p01h_path):
            click.echo(f"  -> {p01h_path}")
        else:
            click.echo("  Failed to generate cmis_page_01h.h")

        # Umbrella header
        umbrella_path = os.path.join(output_dir, "cmis.h")
        with open(umbrella_path, "w", encoding="utf-8") as f:
            f.write(CMIS_UMBRELLA_H)
        click.echo(f"  -> {umbrella_path}")

    except Exception as e:
        click.echo(f"Error during processing: {e}", err=True)

def main():
    cli()
