"""Generate C header for CMIS Low Memory with Bit-Fields, Unions, and Enums."""

import re

def sanitize_name(name):
    """Sanitize a field name for C."""
    clean = ""
    for c in name:
        if c.isalnum() or c == '_':
            clean += c
        elif c == ' ':
            clean += '_'
        else:
            clean += '_'
    clean = clean.strip('_')
    if not clean:
        return "unnamed"
    if clean.lower() in ['register', 'volatile', 'typedef', 'struct', 'enum']:
        clean += "_reg"
    return clean

def clean_c_string(text):
    """Clean up PDF text for C comments."""
    if not text:
        return ""
    # Replace newlines and multiple spaces with single space
    text = " ".join(text.split())
    return text

def format_doxygen(brief, details, access, indent_level=4, width=120):
    """Generate Doxygen-style comment block."""
    lines = []
    has_content = brief or details or access
    
    if not has_content:
        return lines

    indent_str = " " * indent_level
    lines.append(f"{indent_str}/**")
    
    if brief:
        lines.append(f"{indent_str} * @brief {brief}")
    
    if details:
        words = details.split()
        current_line = f"{indent_str} * @details "
        for word in words:
            if len(current_line) + len(word) + 1 > width:
                lines.append(current_line)
                current_line = f"{indent_str} * " + word
            else:
                current_line += word + " "
        if current_line.strip() != f"{indent_str} *":
            lines.append(current_line.rstrip())
            
    if access:
        lines.append(f"{indent_str} * @access {access}")
        
    lines.append(f"{indent_str} */")
    return lines

def parse_bits(bits_str):
    """Parse bits string like '7-4', '3', '5-0' into (msb, lsb)."""
    if not bits_str:
        return (7, 0)
    if '-' in bits_str:
        try:
            msb, lsb = bits_str.split('-')
            return (int(msb), int(lsb))
        except:
            pass
    try:
        val = int(bits_str)
        return (val, val)
    except:
        pass
    return (7, 0)

def generate_c_header(registers, output_path):
    """
    Generate a C struct defining the Low Memory map.
    Uses bit-fields within unions for easy access.
    Groups continuous reserved bytes into arrays.
    Generates Enums for fields referencing tables.
    """
    
    lines = [
        "/* Auto-generated by CMIS2C - CMIS Low Memory Register Map */",
        "#ifndef __CMIS_LOW_MEMORY_H",
        "#define __CMIS_LOW_MEMORY_H",
        "",
        "#include <stdint.h>",
        ""
    ]
    
    # Collect Enums
    field_enums = {}
    
    for reg in registers:
        if 'enum' in reg:
            name = reg.get('Field Name') or reg.get('Name') or reg.get('Register Name', '')
            clean_name = sanitize_name(name)
            if clean_name not in field_enums:
                field_enums[clean_name] = reg['enum']
                
    # Emit Enums
    for field_name, enum_data in field_enums.items():
        enum_name = f"Enums_{field_name}"
        lines.append("typedef enum {")
        for code, enum_info in sorted(enum_data['values'].items()):
            enum_name_raw = enum_info['name']
            if not enum_name_raw or enum_name_raw == '-':
                enum_val_name = f"Reserved_{code}"
            else:
                enum_val_name = sanitize_name(enum_name_raw)
            
            comment = enum_info['name'] if enum_info['name'] != enum_info['desc'] else enum_info['desc']
            lines.append(f"    {enum_name}_{enum_val_name} = {code},  /**< {clean_c_string(comment)} **/")
        lines.append(f"}} {enum_name};")
        lines.append("")
    
    # Organize by byte
    byte_map = {}
    for reg in registers:
        byte_str = reg.get('Byte', '')
        name = reg.get('Field Name') or reg.get('Name') or reg.get('Register Name', '')
        
        if not byte_str or not name or name == '-':
            continue
        
        try:
            if '-' in str(byte_str):
                parts = str(byte_str).split('-')
                start = int(parts[0])
                width = int(parts[1]) - start + 1
                if start < 128:
                    reg['width_bytes'] = width
                    if start not in byte_map:
                        byte_map[start] = []
                    byte_map[start].append(reg)
            else:
                b = int(byte_str)
                if b < 128:
                    if b not in byte_map:
                        byte_map[b] = []
                    byte_map[b].append(reg)
        except (ValueError, TypeError):
            continue

    lines.append("/** @brief CMIS Low Memory Register Map (Bytes 0-127) */")
    lines.append("typedef struct __attribute__((packed)) {")
    lines.append("")

    reserved_start = -1
    reserved_len = 0
    consumed_bytes = set()

    def flush_reserved():
        nonlocal reserved_start, reserved_len
        if reserved_len > 0:
            if reserved_len == 1:
                lines.append(f"    uint8_t reserved_{reserved_start};  /**< r{reserved_start} Reserved */")
            else:
                lines.append(f"    uint8_t reserved_{reserved_start}[{reserved_len}];  /**< r{reserved_start}.. */")
        reserved_len = 0
        reserved_start = -1

    # Detect array starts
    app_array_start = None
    cdb_array_start = None
    
    for b in range(128):
        if b not in byte_map:
            continue
        
        first_reg = byte_map[b][0]
        name0 = first_reg.get('Field Name', '') or first_reg.get('Name', '') or first_reg.get('Register Name', '')
        
        if app_array_start is None and name0 and 'App1' in name0:
            if (b+4) in byte_map:
                next_name = byte_map[b+4][0].get('Field Name', '') or byte_map[b+4][0].get('Name', '')
                if 'App2' in next_name:
                    app_array_start = b
                    for k in range(32):
                        consumed_bytes.add(b + k)
        
        if cdb_array_start is None and name0 and ('CdbStatus1' in name0 or (b == 37 and 'CdbStatus' in name0)):
             if (b+1) in byte_map:
                 next_name = byte_map[b+1][0].get('Field Name', '') or byte_map[b+1][0].get('Name', '')
                 if 'CdbStatus2' in next_name or 'CdbStatus' in next_name:
                     cdb_array_start = b
                     consumed_bytes.add(b)
                     consumed_bytes.add(b+1)
        
        width_bytes = first_reg.get('width_bytes', 1)
        if width_bytes > 1:
            for k in range(1, width_bytes):
                consumed_bytes.add(b + k)

    for b in range(128):
        if b in consumed_bytes:
            flush_reserved()
            if b == app_array_start:
                lines.append("    /** @brief Application Descriptors (AppSel 1-8) */")
                lines.append("    struct {")
                # Generate the 4-byte struct definition
                for offset in range(4):
                    byte_idx = b + offset
                    if byte_idx in byte_map:
                        regs = byte_map[byte_idx]
                        fields = []
                        for r in regs:
                            name = r.get('Field Name', '') or r.get('Name', '') or r.get('Register Name', '')
                            if name and name != '-':
                                clean = re.sub(r'App\d+', '', name).strip('_')
                                bits = r.get('Bits') or r.get('Bit', '')
                                desc = clean_c_string(r.get('Field Description', r.get('Register Description', '')))
                                rtype = clean_c_string(r.get('Type', ''))
                                msb, lsb = parse_bits(bits)
                                fields.append({'name': clean, 'width': msb - lsb + 1, 'lsb': lsb, 'desc': desc, 'type': rtype})
                        
                        fields.sort(key=lambda x: x['lsb'])
                        current_bit = 0
                        for f in fields:
                            gap = f['lsb'] - current_bit
                            if gap > 0:
                                # Unique padding name based on byte offset and bit pos
                                lines.append(f"        uint8_t _pad_{offset}_{current_bit} : {gap};")
                            lines.extend(format_doxygen(f['name'], f['desc'], f['type'], indent_level=8))
                            msb_bit = f['lsb'] + f['width'] - 1
                            if f['width'] == 1:
                                bit_note = f"r{byte_idx}.{f['lsb']}"
                            else:
                                bit_note = f"r{byte_idx}.{msb_bit}-{f['lsb']}"
                            lines.append(f"        uint8_t {f['name']} : {f['width']};  /* {bit_note} */")
                            current_bit = f['lsb'] + f['width']
                        if current_bit < 8:
                            lines.append(f"        uint8_t _pad_{offset}_{current_bit} : {8 - current_bit};")
                    else:
                        lines.append(f"        uint8_t reserved_{offset};")
                lines.append("    } AppDescriptors[8];")
            
            elif b == cdb_array_start:
                lines.append("    /** @brief CDB Status (Instance 1 & 2) */")
                lines.append("    struct {")
                
                struct_lines = []
                fields = [
                    {'name': 'CdbCommandResult', 'width': 6, 'lsb': 0, 
                     'desc': 'The CdbCommandResult field provides more detailed classification for each of the three coarse query results encoded by Bit 7 (CdbIsBusy) and Bit 6 (CdbHasFailed).', 
                     'type': 'RO'},
                    {'name': 'CdbHasFailed', 'width': 1, 'lsb': 6, 
                     'desc': 'Bool: CdbHasFailed bit indicates if there was a failure, after the module has completed execution of the last CDB command.', 
                     'type': 'RO'},
                    {'name': 'CdbIsBusy', 'width': 1, 'lsb': 7, 
                     'desc': 'Bool: CdbIsBusy status bit indicates whether the module is still busy, or idle and ready to accept a new CDB command.', 
                     'type': 'RO'}
                ]
                
                fields.sort(key=lambda x: x['lsb'])
                current_bit = 0
                for f in fields:
                    gap = f['lsb'] - current_bit
                    if gap > 0:
                        pad_name = f"_pad_{b}_{current_bit}"
                        struct_lines.append(f"            uint8_t {pad_name} : {gap};")
                    lines.extend(format_doxygen(f['name'], f['desc'], f['type'], indent_level=12))
                    msb_bit = f['lsb'] + f['width'] - 1
                    if f['width'] == 1:
                        bit_note = f"r{b}.{f['lsb']}"
                    else:
                        bit_note = f"r{b}.{msb_bit}-{f['lsb']}"
                    struct_lines.append(f"            uint8_t {f['name']} : {f['width']};  /* {bit_note} */")
                    current_bit = f['lsb'] + f['width']
                if current_bit < 8:
                    pad_name = f"_pad_{b}_{current_bit}"
                    struct_lines.append(f"            uint8_t {pad_name} : {8 - current_bit};")
                
                lines.append(f"    union {{")
                lines.append(f"        struct {{")
                for line in struct_lines:
                    lines.append(line)
                lines.append(f"        }};")
                # Unique byte accessor name
                lines.append(f"        uint8_t r{b};")
                lines.append(f"    }};")
            else:
                pass
        elif b in byte_map:
            flush_reserved()
            regs = byte_map[b]
            fields = []
            for r in regs:
                name = r.get('Field Name', '') or r.get('Name', '') or r.get('Register Name', '')
                if name and name != '-':
                    clean = sanitize_name(name)
                    bits = r.get('Bits') or r.get('Bit', '')
                    desc = clean_c_string(r.get('Field Description', r.get('Register Description', '')))
                    rtype = clean_c_string(r.get('Type', ''))
                    msb, lsb = parse_bits(bits)
                    fields.append({'name': clean, 'width': msb - lsb + 1, 'lsb': lsb, 'desc': desc, 'type': rtype})
            
            if not fields:
                if reserved_len == 0:
                    reserved_start = b
                reserved_len += 1
            elif len(fields) == 1 and fields[0]['width'] == 8:
                f = fields[0]
                width_bytes = regs[0].get('width_bytes', 1)
                lines.extend(format_doxygen(f['name'], f['desc'], f['type'], indent_level=4))
                if width_bytes == 2:
                    lines.append(f"    uint16_t {f['name']};  /* r{b} */")
                elif width_bytes == 4:
                    lines.append(f"    uint32_t {f['name']};  /* r{b} */")
                else:
                    lines.append(f"    uint8_t {f['name']};  /* r{b} */")
            else:
                fields.sort(key=lambda x: x['lsb'])
                struct_lines = []
                current_bit = 0
                for f in fields:
                    gap = f['lsb'] - current_bit
                    if gap > 0:
                        struct_lines.append(f"            uint8_t _pad_{b}_{current_bit} : {gap};")
                    lines.extend(format_doxygen(f['name'], f['desc'], f['type'], indent_level=8))
                    msb_bit = f['lsb'] + f['width'] - 1
                    if f['width'] == 1:
                        bit_note = f"r{b}.{f['lsb']}"
                    else:
                        bit_note = f"r{b}.{msb_bit}-{f['lsb']}"
                    struct_lines.append(f"            uint8_t {f['name']} : {f['width']};  /* {bit_note} */")
                    current_bit = f['lsb'] + f['width']
                if current_bit < 8:
                    struct_lines.append(f"            uint8_t _pad_{b}_{current_bit} : {8 - current_bit};")
                
                lines.append(f"    union {{")
                lines.append(f"        struct {{")
                for line in struct_lines:
                    lines.append(line)
                lines.append(f"        }};")
                lines.append(f"        uint8_t r{b};")
                lines.append(f"    }};")
        else:
            if reserved_len == 0:
                reserved_start = b
            reserved_len += 1

    flush_reserved()

    lines.append("")
    lines.append("} cmis_low_memory_t;")
    lines.append("")
    lines.append("#if __STDC_VERSION__ >= 202311L")
    lines.append("static_assert(sizeof(cmis_low_memory_t) == 128, \"cmis_low_memory_t must be exactly 128 bytes\");")
    lines.append("#elif __STDC_VERSION__ >= 201112L")
    lines.append("_Static_assert(sizeof(cmis_low_memory_t) == 128, \"cmis_low_memory_t must be exactly 128 bytes\");")
    lines.append("#elif defined(__GNUC__) || defined(__clang__)")
    lines.append("_Static_assert(sizeof(cmis_low_memory_t) == 128, \"cmis_low_memory_t must be exactly 128 bytes\");")
    lines.append("#else")
    lines.append("/* verify manually: sizeof(cmis_low_memory_t) must be 128 */")
    lines.append("#endif")
    lines.append("")
    lines.append("#endif  // __CMIS_LOW_MEMORY_H")

    try:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        return output_path
    except Exception as e:
        print(f"Error writing file: {e}")
        return None
